name: Package Application with Pyinstaller

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: clab_datalogger_receiver_app.spec

      - uses: actions/upload-artifact@v3
        with:
          name: clab_datalogger_receiver
          path: /dist/windows/
