name: Package Application with Pyinstaller

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: qt_app.spec

      - uses: actions/upload-artifact@v2
        with:
          name: clab_datalogger_receiver
          path: src/dist/windows
